spring:
  application:
    name: thymeleaf-template
  datasource:
    url: jdbc:postgresql://192.168.56.6:5432/template
    username: template_user
    password: template_pwd
    driver-class-name: org.postgresql.Driver
