spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  application:
    name: thymeleaf-template
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Asia/Seoul

mybatis:
  type-aliases-package: com.example.template.common.map
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true

logging:
  level:
    com.example.template.mapper: DEBUG

file:
  upload-dir: C:/uploads/

---
spring:
  config:
    activate:
      on-profile: redis
  session:
    redis:
      namespace: template:session
  data:
    redis:
      host: localhost
      port: 6379
      
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID