spring:
  application:
    name: thymeleaf-template
  profiles:
    active: local-inmemory
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    time-zone: Asia/Seoul

mybatis:
  type-aliases-package: com.example.template.common.map
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true

logging:
  level:
    com.example.template.mapper: DEBUG

file:
  upload-dir: C:/uploads/

server:
  servlet:
    session:
      timeout: 30m