spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  application:
    name: thymeleaf-template
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ENC(Bav0nZVGC8LWIFAP4Cpsgcc3mBkjuZAN4VxariXy4HQR7pqE42WvHFDAmYQbo2w0xttkfHEJcQ0=)
    username: ENC(PSEk9njKgT3pkPA0ZMnC9EFJ/I/lejbc)
    password: ENC(fYpG8QJTwikWxXsHWUyu8g==)
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Asia/Seoul

mybatis:
  type-aliases-package: com.example.template.common.map
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true

logging:
  level:
    com.example.template.mapper: DEBUG

file:
  upload-dir: C:/uploads/

---
spring:
  config:
    activate:
      on-profile: redis
  session:
    redis:
      namespace: template:session
  data:
    redis:
      host: ENC(nBhHPTB43jkGxv4cJ6YEigPXyayY5e/X)
      port: ENC(AJ4p3TxS+59TVOjPgbJkuA==)
      password: ENC(pZ0ADqWJ0eLK6NVqpicCdw==)
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID