spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/template
    username: template_user
    password: template_pwd
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

file:
  upload-dir: C:/apps/template/uploads/

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
