spring:
  application:
    name: thymeleaf-template
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    redis:
      namespace: template:session
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Asia/Seoul


server:
  servlet:
    session:
      cookie:
        name: JSESSIONID


mybatis:
  type-aliases-package: com.example.template.common.map
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true


logging:
  level:
    com.example.template.mapper: DEBUG

file:
  upload-dir: C:/uploads/

