spring:
  datasource:
    primary:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 1234
      driver-class-name: org.postgresql.Driver
    secondary:
      jdbc-url: jdbc:postgresql://localhost:5433/postgres
      username: postgres
      password: 1234
      driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

file:
  upload-dir: C:/apps/template/uploads/

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
