spring:
  application:
    name: ipro
  profiles:
    active: local-inmemory
  
app:
  datasource:
    secondary:
      enabled: false  # Secondary DB 활성화 여부 (true/false)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    time-zone: Asia/Seoul


server:
  servlet:
    session:
      timeout: 30m
